#!/bin/bash
# Invoke the Forever module (to START our Node.js server).
rm err.log
export NODE_ENV=production 
./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
index.js
